# Generated by Django 5.2.9 on 2026-01-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device_fingerprint",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Fingerprint Dispositivo"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_device_fingerprint",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Último Fingerprint"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP Último Login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="signup_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP de Cadastro"
            ),
        ),
    ]
