# Generated by Django 4.2.7 on 2026-01-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="plan_slug",
            field=models.CharField(
                default="freemium", max_length=20, verbose_name="Plan Slug"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("freemium", "Freemium - Grátis"),
                    ("monthly", "Premium Mensal - 499 MZN"),
                    ("quarterly", "Premium Trimestral - 1299 MZN"),
                    ("yearly", "Premium Anual - 4499 MZN"),
                ],
                max_length=20,
                verbose_name="Plano",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativa"),
                    ("expired", "Expirada"),
                    ("cancelled", "Cancelada"),
                    ("pending", "Pendente"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
