# Generated by Django 4.2.7 on 2026-01-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subscriptions",
            "0002_subscription_plan_slug_alter_subscription_plan_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="MZN", max_length=3, verbose_name="Moeda"),
        ),
        migrations.AddField(
            model_name="payment",
            name="paysuite_reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Referência PaySuite"
            ),
        ),
    ]
