# Generated by Django 4.2.7 on 2026-01-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_payment_currency_payment_paysuite_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("freemium", "Freemium - Grátis"),
                    ("starter", "Starter - 299 MZN"),
                    ("pro", "Pro - 599 MZN"),
                    ("vip", "VIP - 1499 MZN"),
                ],
                max_length=20,
                verbose_name="Plano",
            ),
        ),
    ]
