# Generated by Django 5.2.9 on 2026-01-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0005_migrate_old_plans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("freemium", "Freemium - Grátis"),
                    ("teste", "Teste - 1 MZN"),
                    ("starter", "Starter - 299 MZN"),
                    ("pro", "Pro - 599 MZN"),
                    ("vip", "VIP - 1499 MZN"),
                ],
                max_length=20,
                verbose_name="Plano",
            ),
        ),
    ]
