# Generated by Django 4.2.7 on 2026-02-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0006_alter_subscription_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paysuite_reference",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Referência PaySuite",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("monthly", "Mensal - 499 MZN"),
                    ("quarterly", "Trimestral - 1299 MZN"),
                    ("yearly", "Anual - 4499 MZN"),
                ],
                max_length=20,
                verbose_name="Plano",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan_slug",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Plan Slug"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativa"),
                    ("expired", "Expirada"),
                    ("cancelled", "Cancelada"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
