# Generated by Django 5.0.1 on 2025-12-29 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("country", models.CharField(max_length=50, verbose_name="País")),
                ("logo", models.URLField(blank=True, verbose_name="Logo")),
                (
                    "api_football_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="API Football ID"
                    ),
                ),
                (
                    "football_data_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Football Data ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa?")),
                ("priority", models.IntegerField(default=0, verbose_name="Prioridade")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado Em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado Em"),
                ),
            ],
            options={
                "verbose_name": "Liga",
                "verbose_name_plural": "Ligas",
                "ordering": ["-priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["api_football_id"],
                        name="matches_lea_api_foo_ea6812_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="matches_lea_is_acti_5738f5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("logo", models.URLField(blank=True, verbose_name="Logo")),
                (
                    "country",
                    models.CharField(blank=True, max_length=50, verbose_name="País"),
                ),
                (
                    "api_football_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="API Football ID"
                    ),
                ),
                (
                    "football_data_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Football Data ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado Em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado Em"),
                ),
            ],
            options={
                "verbose_name": "Time",
                "verbose_name_plural": "Times",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["api_football_id"],
                        name="matches_tea_api_foo_f5062d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_date", models.DateTimeField(verbose_name="Data/Hora")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendada"),
                            ("live", "Ao Vivo"),
                            ("finished", "Finalizada"),
                            ("postponed", "Adiada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "round",
                    models.CharField(blank=True, max_length=50, verbose_name="Rodada"),
                ),
                (
                    "home_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Gols Casa"
                    ),
                ),
                (
                    "away_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Gols Visitante"
                    ),
                ),
                (
                    "api_football_id",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="API Football ID",
                    ),
                ),
                (
                    "football_data_id",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Football Data ID",
                    ),
                ),
                (
                    "stats_cache",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Cache de Estatísticas"
                    ),
                ),
                (
                    "last_stats_update",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Atualização Stats"
                    ),
                ),
                (
                    "is_analysis_available",
                    models.BooleanField(
                        default=True, verbose_name="Análise Disponível?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado Em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado Em"),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="matches.league",
                        verbose_name="Liga",
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="matches.team",
                        verbose_name="Time Visitante",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="matches.team",
                        verbose_name="Time Casa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partida",
                "verbose_name_plural": "Partidas",
                "ordering": ["-match_date"],
                "indexes": [
                    models.Index(
                        fields=["match_date", "status"],
                        name="matches_mat_match_d_c72ea9_idx",
                    ),
                    models.Index(
                        fields=["league", "match_date"],
                        name="matches_mat_league__a45dfd_idx",
                    ),
                    models.Index(
                        fields=["api_football_id"],
                        name="matches_mat_api_foo_e96766_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                check=models.Q(("home_team", models.F("away_team")), _negated=True),
                name="different_teams",
            ),
        ),
    ]
