# Generated by Django 5.0.1 on 2025-12-29 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction",
                    models.CharField(
                        choices=[
                            ("home", "Vitória Casa"),
                            ("draw", "Empate"),
                            ("away", "Vitória Visitante"),
                        ],
                        max_length=10,
                        verbose_name="Predição",
                    ),
                ),
                (
                    "confidence",
                    models.IntegerField(
                        choices=[
                            (1, "⭐ Baixa"),
                            (2, "⭐⭐ Média-Baixa"),
                            (3, "⭐⭐⭐ Média"),
                            (4, "⭐⭐⭐⭐ Alta"),
                            (5, "⭐⭐⭐⭐⭐ Muito Alta"),
                        ],
                        verbose_name="Confiança",
                    ),
                ),
                ("home_probability", models.FloatField(verbose_name="Prob. Casa (%)")),
                (
                    "draw_probability",
                    models.FloatField(verbose_name="Prob. Empate (%)"),
                ),
                (
                    "away_probability",
                    models.FloatField(verbose_name="Prob. Visitante (%)"),
                ),
                (
                    "home_xg",
                    models.FloatField(blank=True, null=True, verbose_name="xG Casa"),
                ),
                (
                    "away_xg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="xG Visitante"
                    ),
                ),
                ("analysis_data", models.JSONField(verbose_name="Dados da Análise")),
                ("reasoning", models.TextField(verbose_name="Raciocínio")),
                ("key_factors", models.JSONField(verbose_name="Fatores Chave")),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Predição Correta?"
                    ),
                ),
                (
                    "actual_result",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Resultado Real"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado Em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado Em"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="matches.match",
                        verbose_name="Partida",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análise",
                "verbose_name_plural": "Análises",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="analysis_an_user_id_8f0fa9_idx",
                    ),
                    models.Index(
                        fields=["match", "is_correct"],
                        name="analysis_an_match_i_cfefd3_idx",
                    ),
                ],
                "unique_together": {("user", "match")},
            },
        ),
    ]
