# Generated by Django 4.2.7 on 2025-12-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="analysis",
            field=models.TextField(
                blank=True, null=True, verbose_name="Análise Completa"
            ),
        ),
    ]
