# Generated by Django 4.2.7 on 2026-01-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_analysis_analysis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysis",
            name="analysis",
        ),
        migrations.CreateModel(
            name="DailyBet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, verbose_name="Data do Bilhete"),
                ),
                (
                    "bet_type",
                    models.CharField(
                        choices=[
                            ("multiple", "Bilhete Múltiplo"),
                            ("value", "Value Bet"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "selections",
                    models.JSONField(
                        help_text="Lista de apostas do bilhete", verbose_name="Seleções"
                    ),
                ),
                (
                    "total_odd",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Odd Total"
                    ),
                ),
                (
                    "fair_odd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Odd Justa",
                    ),
                ),
                (
                    "combined_probability",
                    models.FloatField(
                        help_text="Para bilhetes: produto das probabilidades",
                        verbose_name="Prob. Combinada",
                    ),
                ),
                (
                    "expected_value",
                    models.FloatField(
                        help_text="Expected Value em porcentagem", verbose_name="EV %"
                    ),
                ),
                (
                    "suggested_stake",
                    models.FloatField(
                        default=1.0, verbose_name="Stake Sugerido (unidades)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando"),
                            ("won", "Ganhou"),
                            ("lost", "Perdeu"),
                            ("partial", "Parcial"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "actual_result",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Resultado Real"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Validado em"
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(default=False, verbose_name="Validado"),
                ),
            ],
            options={
                "verbose_name": "Aposta Diária",
                "verbose_name_plural": "Apostas Diárias",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["date", "bet_type"], name="analysis_da_date_353143_idx"
                    ),
                    models.Index(
                        fields=["status"], name="analysis_da_status_05f4c3_idx"
                    ),
                    models.Index(
                        fields=["is_validated", "date"],
                        name="analysis_da_is_vali_ea2f6a_idx",
                    ),
                ],
            },
        ),
    ]
