# Generated by Django 4.2.7 on 2026-02-15 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analysis", "0003_add_daily_bet_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        choices=[
                            ("generate_daily_bets", "Gerar Bilhetes Diários"),
                            ("validate_daily_bets", "Validar Bilhetes"),
                        ],
                        max_length=50,
                        verbose_name="Task",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Celery Task ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Em Execução"),
                            ("success", "Sucesso"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciado Em"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalizado Em"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duração (segundos)"
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Dados do Resultado"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensagem de Erro"),
                ),
                (
                    "matches_analyzed",
                    models.IntegerField(default=0, verbose_name="Partidas Analisadas"),
                ),
                (
                    "bets_generated",
                    models.IntegerField(default=0, verbose_name="Apostas Geradas"),
                ),
                (
                    "bets_validated",
                    models.IntegerField(default=0, verbose_name="Apostas Validadas"),
                ),
                (
                    "api_calls",
                    models.IntegerField(default=0, verbose_name="Chamadas API"),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("celery", "Automático (Celery)"),
                            ("manual", "Manual (Admin)"),
                        ],
                        default="celery",
                        max_length=20,
                        verbose_name="Iniciado Por",
                    ),
                ),
                (
                    "triggered_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execução de Task",
                "verbose_name_plural": "Execuções de Tasks",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["task_name", "-started_at"],
                        name="analysis_ta_task_na_8de894_idx",
                    ),
                    models.Index(
                        fields=["status", "-started_at"],
                        name="analysis_ta_status_4134e1_idx",
                    ),
                ],
            },
        ),
    ]
