# Generated by Django 4.2.7 on 2026-02-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_taskexecution"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskexecution",
            name="bets_created",
            field=models.IntegerField(
                default=0,
                help_text="Apostas criadas até agora",
                verbose_name="Apostas Criadas",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="current_stage",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Etapa de execução: searching, analyzing, creating, completed",
                max_length=50,
                verbose_name="Etapa Atual",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="last_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp da última atualização de progresso",
                null=True,
                verbose_name="Última Atualização",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="matches_found",
            field=models.IntegerField(
                default=0,
                help_text="Total de partidas encontradas para análise",
                verbose_name="Partidas Encontradas",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="matches_processed",
            field=models.IntegerField(
                default=0,
                help_text="Partidas já processadas/analisadas",
                verbose_name="Partidas Processadas",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="progress_log",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Log detalhado das etapas de execução",
                verbose_name="Log de Progresso",
            ),
        ),
    ]
